### ISSUE TITLE
PostgresSaver Implementation

### ISSUE THREAD

**Issue by RossellaCarone** [langchain-ai/langchain-postgres#104] opened 2024-08-08 12:22 UTC
I noticed that an earlier version included the PostgresSaver checkpointer. However, it seems to have been removed. Can you provide information on when it will be available again?

**Comment by eyurtsev** [comment] 2024-08-09 17:16
Duplicate of https://github.com/langchain-ai/langchain-postgres/issues/81 (@RossellaCarone see that issue)

**Closed by eyurtsev** 2024-08-09 17:16 UTC
